# Dependencies
markdown:         redcarpet
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

pygments:         true

# Permalinks
permalink:        pretty

gems:           ['jekyll-multiple-languages']

# Server
baseurl:          /
encoding:         UTF-8

exclude:
  - "conf"
  - "tools"

info:
  site_name:    Cube SDK

meta:
  description:  A android development framework. It makes loading image and network request easy.
  keywords:     Cube-SDK, Android development framework, Image Loader, Easy netwrok request.
  author:       liaohuqiu@gmail.com

languages:          ['en', 'cn']
language_default:   "en"

left_nav:
  en:
    path:       /
    title:      Cube
    items:
      - path:     /imageloader
        title:    Image Loader
      - path:     /request
        title:    Request
      - path:     /request-cache
        title:    Cache for Request
      - path:     /views
        title:    Component Views
      - path:     /javadoc
        title:    "Javadoc"
  cn:
    path:     /cn
    title:    Cube
    items:
      - path:     /cn/imageloader
        title:    图片加载组件
      - path:     /cn/request
        title:    网络请求
      - path:     /cn/cache
        title:    缓存
      - path:     /cn/request-cache
        title:    请求缓存
      - path:     /cn/views
        title:    常用组件
      - path:     /cn/load-more
        title:    加载更多
      - path:     /javadoc
        title:    "Javadoc"

right_nav:
  - title:    English
    url:      /
  - title:    简体中文
    url:      /cn
  - title:    Fork on Github
    url:     https://github.com/liaohuqiu/cube-sdk

analytics:
  google:
    account:    UA-43024238-2

download:
  rep:          https://github.com/liaohuqiu/cube-sdk
  dist:         https://github.com/liaohuqiu/cube-sdk/archive/master.zip
  apk:          https://github.com/liaohuqiu/cube-sdk/raw/master/cube-sdk-sample.apk
  qrcode:       /assets/img/qrcode.png
  google_play:   /
